site_name: Python pro ArcGIS
site_author: Vojta Barták
repo_url: https://github.com/vojta-bartak/Python-for-ArcGIS-CZU
theme:
  name: gitbook
plugins: []
nav:
    - Home: index.md
    - Model Builder: 
        - 'Lekce 1: Tvorba modelu': 'Lekce 1 Model Builder I.md'
        - 'Lekce 2: Uživatelské rozhraní': 'Lekce 2 Model Builder II.md'
    - Python:
        - 'Lekce 3: Rozjezd Pythonu': 'Lekce 3 Jak a kde napsat a spustit program v Pythonu.md'
        - 'Lekce 4: Proměnné a datové typy': 'Lekce 4 Proměnné a datové typy.md'
        - 'Lekce 5: Cykly a podmínky': 'Lekce 5 Řídící struktury programu - cykly a podmínky.md'
    - O mně...: about_me.md