site_name: Python pro ArcGIS
site_author: Vojta Barták
copyright: FŽP ČZU Praha
repo_url: https://github.com/vojta-bartak/Python-for-ArcGIS-CZU
theme:
  name: gitbook
plugins: []
nav:
    - Home: index.md
    - Model Builder: 
        - 'Lekce 1: Tvorba modelu': 'lekce1.md'
        - 'Lekce 2: Uživatelské rozhraní': 'lekce2.md'
    - O mně...: about_me.md